---
"Product ID": "test"
"Clusters and AWS Resources Topology 1: Title": "TODO"
"Clusters and AWS Resources Topology 1: AWS Calculator Link": "TODO"
"Clusters and AWS Resources Topology 1: Short Description": "TODO"
"Clusters and AWS Resources Topology 1: Long Description": "TODO"
"Clusters and AWS Resources Topology 1: CloudFormation Template URL": "TODO"
"Clusters and AWS Resources Topology 1: Architecture Diagram URL": https://ordinaryexperts.com/img/services/oe_drupal_patterns_topology_diagram.png
