---
"Product ID": "TODO"
"Product Code": "TODO"
"Accessibility": "TODO"
"SKU": "TODO"
"Software by": "Ordinary Experts"
"Title": "TODO"
"Short Description": "TODO"
"Full Description": "TODO"
"Highlight1": "TODO"
"Highlight2": "TODO"
"Highlight3": "TODO"
"Product Category1": "TODO"
"Product Category2": "TODO"
"Product Category3": "TODO"
"Search Keywords": "TODO"
"Resource1_Name": "TODO"
"Resource1_URL": "TODO"
"Resource2_Name": "TODO"
"Resource2_URL": "TODO"
"Resource3_Name": "TODO"
"Resource3_URL": "TODO"
"Image URL": "TODO"
"Product Video": "TODO"
"Support Offered": "TODO"
"Support Information": "TODO"
"Support Detail": "TODO"
"Refund and Cancelation Policy": "TODO"
"Type": "TODO"
"us-east-1 AMI ID": "TODO"
"AMI Virtualization Type": "TODO"
"Architecture": "TODO"
"AFI": "TODO"
"Operating System": "TODO"
"Operating System Version": "TODO"
"Operating System Username": "TODO"
"PIOPS Total": "TODO"
"AWS Services Required": "TODO"
"3rd Party Software Included": "TODO"
"Version Title": "TODO"
"Release Notes": "TODO"
"Upgrade Instructions": "TODO"
"Product Access Instructions": "TODO"
"Endpoint URL Protocol": "TODO"
"Endpoint URL Port": "TODO"
"Endpoint URL Relative URL": "TODO"
# region availability fields are here, i.e. "me-south-1 Availability"
"End User License Agreement URL": "TODO"
"Make available in all future U.S. regions": "FALSE"
"Make available in all future non-U.S. regions": "FALSE"
"Recommended Instance Type": "m5.xlarge"
"Make available for all future instance types": "FALSE"
# instance availability fields are here, i.e. "z1d.12xlarge Availability"
"Pricing Model": "Hourly_Annual"
"Product Tax Code": "A_GEN_NOTAX"
"BYOL URL": ""
"Free Trial Instance Count": "1"
"Free Trial Duration": "5"
# instance Hourly Price fields are here, i.e. "z1d.12xlarge Hourly Price"
"Monthly Price": ""
# instance Annual Price fields are here, i.e. "z1d.12xlarge Annual Price"
"Security Group Rule 1": ""
"Security Group Rule 2": ""
"Security Group Rule 3": ""
"Security Group Rule 4": ""
"Security Group Rule 5": ""
"Security Group Rule 6": ""
"Security Group Rule 7": ""
"Security Group Rule 8": ""
"Security Group Rule 9": ""
"Security Group Rule 10": ""
"Security Group Rule 11": ""
"Security Group Rule 12": ""
"FCP Category": ""
"FCP Unit": ""
"FCP Dimension1 Name": ""
"FCP Dimension1 Description": ""
"FCP Dimension1 Rate": ""
"FCP Dimension2 Name": ""
"FCP Dimension2 Description": ""
"FCP Dimension2 Rate": ""
"FCP Dimension3 Name": ""
"FCP Dimension3 Description": ""
"FCP Dimension3 Rate": ""
"FCP Dimension4 Name": ""
"FCP Dimension4 Description": ""
"FCP Dimension4 Rate": ""
"FCP Dimension5 Name": ""
"FCP Dimension5 Description": ""
"FCP Dimension5 Rate": ""
"FCP Dimension6 Name": ""
"FCP Dimension6 Description": ""
"FCP Dimension6 Rate": ""
"FCP Dimension7 Name": ""
"FCP Dimension7 Description": ""
"FCP Dimension7 Rate": ""
"FCP Dimension8 Name": ""
"FCP Dimension8 Description": ""
"FCP Dimension8 Rate": ""
"FCP Dimension9 Name": ""
"FCP Dimension9 Description": ""
"FCP Dimension9 Rate": ""
"FCP Dimension10 Name": ""
"FCP Dimension10 Description": ""
"FCP Dimension10 Rate": ""
"FCP Dimension11 Name": ""
"FCP Dimension11 Description": ""
"FCP Dimension11 Rate": ""
"FCP Dimension12 Name": ""
"FCP Dimension12 Description": ""
"FCP Dimension12 Rate": ""
"FCP Dimension13 Name": ""
"FCP Dimension13 Description": ""
"FCP Dimension13 Rate": ""
"FCP Dimension14 Name": ""
"FCP Dimension14 Description": ""
"FCP Dimension14 Rate": ""
"FCP Dimension15 Name": ""
"FCP Dimension15 Description": ""
"FCP Dimension15 Rate": ""
"FCP Dimension16 Name": ""
"FCP Dimension16 Description": ""
"FCP Dimension16 Rate": ""
"FCP Dimension17 Name": ""
"FCP Dimension17 Description": ""
"FCP Dimension17 Rate": ""
"FCP Dimension18 Name": ""
"FCP Dimension18 Description": ""
"FCP Dimension18 Rate": ""
"FCP Dimension19 Name": ""
"FCP Dimension19 Description": ""
"FCP Dimension19 Rate": ""
"FCP Dimension20 Name": ""
"FCP Dimension20 Description": ""
"FCP Dimension20 Rate": ""
"FCP Dimension21 Name": ""
"FCP Dimension21 Description": ""
"FCP Dimension21 Rate": ""
"FCP Dimension22 Name": ""
"FCP Dimension22 Description": ""
"FCP Dimension22 Rate": ""
"FCP Dimension23 Name": ""
"FCP Dimension23 Description": ""
"FCP Dimension23 Rate": ""
"FCP Dimension24 Name": ""
"FCP Dimension24 Description": ""
"FCP Dimension24 Rate": ""
"Clusters and AWS Resources Topology 1: Title": "TODO"
"Clusters and AWS Resources Topology 1: AWS Calculator Link": "TODO"
"Clusters and AWS Resources Topology 1: Short Description": "TODO"
"Clusters and AWS Resources Topology 1: Long Description": "TODO"
"Clusters and AWS Resources Topology 1: CloudFormation Template URL": "TODO"
"Clusters and AWS Resources Topology 1: Architecture Diagram URL": https://ordinaryexperts.com/img/services/oe_drupal_patterns_topology_diagram.png
"Clusters and AWS Resources Topology 2: Title": ""
"Clusters and AWS Resources Topology 2: AWS Calculator Link": ""
"Clusters and AWS Resources Topology 2: Short Description": ""
"Clusters and AWS Resources Topology 2: Long Description": ""
"Clusters and AWS Resources Topology 2: CloudFormation Template URL": ""
"Clusters and AWS Resources Topology 2: Architecture Diagram URL": ""
"Clusters and AWS Resources Topology 3: Title": ""
"Clusters and AWS Resources Topology 3: AWS Calculator Link": ""
"Clusters and AWS Resources Topology 3: Short Description": ""
"Clusters and AWS Resources Topology 3: Long Description": ""
"Clusters and AWS Resources Topology 3: CloudFormation Template URL": ""
"Clusters and AWS Resources Topology 3: Architecture Diagram URL": ""


