# Workflow to test Drupal pattern with taskcat
name: AWS Patterns Ordinary Experts Patterns Drupal CI

on:
  push:
    branches: [ master, develop, 'hotfix/*', 'release/*', 'feature/*' ]
    tags: [ '*' ]
  pull_request:
    branches: [ 'feature/*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 'ubuntu:focal'
    steps:
    - uses: actions/checkout@v2
    - name: setup
      run: bash setup-env.sh
      working-directory: ${{ github.workspace }}
    - name: taskcat
      run: "cd cdk && cdk synth > ../test/template.yaml && cd ../test && taskcat test run"
      working-directory: ${{ github.workspace }}
