# run all tests once at 11pm pst daily
name: Test Nightly CI

on:
  schedule:
    - cron: '0 6 * * *' # run at 11pm pst

jobs:
  taskcat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: make build
      - name: test
        run: make test
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.OE_PATTERNS_TASKCAT_DEV_GITHUB_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.OE_PATTERNS_TASKCAT_DEV_GITHUB_AWS_SECRET_ACCESS_KEY }}
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: taskcat_outputs
          path: test/taskcat_outputs/
      - name: clean snapshots
        if: always()
        run: make clean-snapshots-tcat
