# run all tests once weekly Monday 9am
name: Test Weekly CI

on:
  schedule:
    - cron: '0 16 * * 1' # run Mondays at 9am pacific

jobs:
  taskcat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: make build
      - name: test
        run: make test-all
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.OE_PATTERNS_TASKCAT_DEV_GITHUB_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.OE_PATTERNS_TASKCAT_DEV_GITHUB_AWS_SECRET_ACCESS_KEY }}
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: taskcat_outputs
          path: test/taskcat_outputs/
      - name: clean snapshots
        if: always()
        run: make clean-snapshots-tcat-all-regions
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.OE_PATTERNS_TASKCAT_DEV_GITHUB_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.OE_PATTERNS_TASKCAT_DEV_GITHUB_AWS_SECRET_ACCESS_KEY }}
      - name: clean logs
        if: always()
        run: make clean-logs-tcat-all-regions
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.OE_PATTERNS_TASKCAT_DEV_GITHUB_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.OE_PATTERNS_TASKCAT_DEV_GITHUB_AWS_SECRET_ACCESS_KEY }}
